# nginx/values.yaml

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: 3.38.170.182
      paths:
        - path: /
          pathType: ImplementationSpecific

image:
  repository: public.ecr.aws/k3f1h3u2/btc3-ecr
  tag: latest  # 또는 원하는 이미지 버전으로 변경
  pullPolicy: IfNotPresent

